### ISSUE TITLE
TypeError: unsupported operand type(s) for /: 'float' and 'str

### ISSUE THREAD

**Issue by costantinoai** [compneuro-ncu/fmridenoise#84]
I got some errors today when running fmridenoise-dev in docker. The errors were related to the file denoising.py: it seems that in line 136 `t_r=self.inputs.tr_dict[task])` t_r would result in a string value that will be used in case of no high/low pass filter flags, returning a nilearn error `TypeError: unsupported operand type(s) for /: 'float' and 'str'` during the denoising step

I solved my issue by changing line 136 into `t_r=float(self.inputs.tr_dict[task]))`

**Comment by SiegfriedWagner** [comment]
Make pr, I will check on Monday.
